version: "3.8"

services:
  nexus:
    image: sonatype/nexus3
    container_name: nexus
    ports:
      - "8081:8081"
    volumes:
      - nexus-data:/nexus-data
    environment:
      - NEXUS_SECURITY_RANDOMPASSWORD=false
      - NEXUS_CONTEXT=/nexus
    deploy:
      resources:
        limits:
          memory: 1g
    networks:
      - dev-network

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
      - ./jenkins.yaml:/var/jenkins_home/casc_configs/jenkins.yaml
    environment:
      - CASC_JENKINS_CONFIG=/var/jenkins_home/casc_configs/jenkins.yaml
    deploy:
      resources:
        limits:
          memory: 1g
    networks:
      - dev-network

  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    ports:
      - "80:80"
      - "443:443"
      - "2222:22"
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.example.com'
        gitlab_rails['initial_root_password'] = 'admin_password'
        gitlab_rails['initial_shared_runners_registration_token'] = 'token'
    deploy:
      resources:
        limits:
          memory: 1g
    networks:
      - dev-network

volumes:
  nexus-data:
  jenkins-data:
  gitlab-config:
  gitlab-logs:
  gitlab-data:

networks:
  dev-network:
