jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "admin_password"
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
